import { PARKING_FEES } from './policyContent';
import { buildingToLLC } from './buildings';
import { normalizeAddress } from './addressNormalizer';
import { getInsuranceTranslations, PrintLang } from './insurancePrintTranslations';

interface PrintData {
  tenantName: string;
  buildingAddress: string;
  unitNumber: string;
  phone?: string;
  email?: string;
  staffName: string;
  date?: string;
}

function findLLCForAddress(address: string): string {
  const normalized = normalizeAddress(address);
  const llc = buildingToLLC[normalized];
  return llc ? `${llc} c/o Stanton Management LLC` : 'Stanton Management LLC';
}

function printStyles(): string {
  return `
    @import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&family=Inter:wght@400;500;600;700&display=swap');
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', sans-serif; color: #1a1a1a; background: #fdfcfa; padding: 48px 64px; font-size: 11px; line-height: 1.65; }
    .company-header { text-align: center; padding-bottom: 20px; margin-bottom: 28px; border-bottom: 2px solid #1a2744; }
    .company-header h1 { font-family: 'Libre Baskerville', serif; font-size: 20px; color: #1a2744; letter-spacing: 2px; margin-bottom: 6px; }
    .company-header p { font-size: 10px; color: #6b7280; letter-spacing: 0.5px; }
    .form-title { font-family: 'Libre Baskerville', serif; font-size: 16px; color: #1a2744; text-align: center; margin-bottom: 28px; text-transform: uppercase; letter-spacing: 1px; }
    h2 { font-family: 'Libre Baskerville', serif; font-size: 13px; color: #1a2744; margin-top: 24px; margin-bottom: 10px; padding-bottom: 4px; border-bottom: 1px solid #d1d5db; }
    h3 { font-family: 'Libre Baskerville', serif; font-size: 12px; color: #2d3f5f; margin-top: 18px; margin-bottom: 8px; }
    p { margin-bottom: 8px; font-size: 11px; }
    strong { font-weight: 600; }
    ul, ol { padding-left: 18px; margin-bottom: 10px; }
    li { margin-bottom: 4px; font-size: 11px; }
    hr { border: none; border-top: 1px solid #d1d5db; margin: 20px 0; }
    table { width: 100%; border-collapse: collapse; margin: 14px 0; font-size: 10px; }
    th, td { border: 1px solid #d1d5db; padding: 7px 12px; text-align: left; }
    th { background: #f8f7f5; font-weight: 600; color: #1a2744; font-size: 10px; text-transform: uppercase; letter-spacing: 0.3px; }
    .field { margin-bottom: 14px; }
    .field-label { font-weight: 600; font-size: 10px; color: #1a2744; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; }
    .field-value { font-size: 11px; padding: 2px 0; border-bottom: 1px solid #d1d5db; min-height: 22px; }
    .field-blank { border-bottom: 1px solid #1a1a1a; height: 24px; width: 100%; }
    .callout { background: #f8f7f5; border-left: 3px solid #8b7355; padding: 12px 16px; margin: 14px 0; font-size: 11px; }
    .callout strong { color: #1a2744; }
    .prefilled { color: #1a2744; font-weight: 600; font-size: 12px; }
    .signature-block { margin-top: 32px; display: flex; gap: 40px; }
    .signature-item { flex: 1; }
    .signature-label { font-size: 9px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; }
    .signature-line { border-bottom: 1px solid #1a1a1a; height: 28px; width: 100%; }
    .checkbox-row { display: flex; align-items: flex-start; gap: 8px; margin-bottom: 8px; font-size: 11px; }
    .checkbox { width: 14px; height: 14px; border: 1.5px solid #1a2744; flex-shrink: 0; margin-top: 2px; }
    .checkbox.checked { background: #1a2744; }
    .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #d1d5db; font-size: 9px; color: #6b7280; text-align: center; }
    .page-break { page-break-before: always; padding-top: 48px; }
    @media print { body { padding: 24px 40px; background: white; } .page-break { page-break-before: always; padding-top: 24px; } }
  `;
}

function companyHeader(): string {
  return `
    <div class="company-header">
      <h1>STANTON MANAGEMENT</h1>
      <p>421 Park Street, Hartford CT 06106 &nbsp;|&nbsp; (860) 993-3401</p>
    </div>
  `;
}

function field(label: string, value?: string): string {
  return `
    <div class="field">
      <div class="field-label">${label}</div>
      ${value ? `<div class="field-value">${value}</div>` : '<div class="field-blank"></div>'}
    </div>
  `;
}

function signatureBlock(labels: string[]): string {
  return `
    <div class="signature-block">
      ${labels.map(l => `
        <div class="signature-item">
          <div class="signature-label">${l}</div>
          <div class="signature-line"></div>
          <div style="font-size: 9px; color: #6b7280; margin-top: 4px;">Date: _______________</div>
        </div>
      `).join('')}
    </div>
  `;
}

function footer(date: string): string {
  return `<div class="footer">Generated by Stanton Management &nbsp;|&nbsp; ${date}</div>`;
}

// ── Vehicle Addendum ──

interface VehicleData {
  type: string;
  make: string;
  model: string;
  year: string;
  color: string;
  plate: string;
  monthlyFee: number;
}

export function renderVehicleAddendum(data: PrintData, vehicle: VehicleData): string {
  const date = data.date || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Vehicle & Parking Addendum</title><style>${printStyles()}</style></head><body>
    ${companyHeader()}
    <div class="form-title">Vehicle & Parking Addendum to Rental Agreement</div>
    ${field('Tenant Name(s)', data.tenantName)}
    ${field('Unit Address', `${data.buildingAddress} - Unit ${data.unitNumber}`)}
    ${field('Date', date)}
    <hr>
    <h2>Parking Fees</h2>
    <table>
      <tr><th>Vehicle Type</th><th>Monthly Fee</th></tr>
      <tr><td>Moped, motorcycle, ATV, scooter</td><td>$${PARKING_FEES.moped}</td></tr>
      <tr><td>Sedan, SUV, Pickup (under 20 ft)</td><td>$${PARKING_FEES.standard}</td></tr>
      <tr><td>Oversized vehicles (over 20 ft)</td><td>$${PARKING_FEES.oversized}</td></tr>
      <tr><td>Boats, trailers, equipment</td><td>$${PARKING_FEES.boats}+ (approval required)</td></tr>
    </table>
    <hr>
    <p>You understand that parking is not included with this Lease and that we may or may NOT allow you to park your vehicles on the property. We reserve the right to restrict, condition, or revoke any prior authorization given at any time.</p>
    <p>You also acknowledge that if we allow you to park on the property, you must register your vehicle with us and pay parking fees as follows:</p>
    <p><strong>PARKING FEES:</strong> <span class="prefilled">$${vehicle.monthlyFee} per vehicle per month</span></p>
    <p><strong>PERMIT LIMIT:</strong> Each tenant is limited to one (1) parking permit. Additional permits may be available on a first-come, first-served basis after all tenants in the building have had the opportunity to obtain their first permit. Not all buildings allow a second permit. Contact the office for availability.</p>
    <hr>
    <h2>Terms and Conditions</h2>
    <p>All authorized vehicles shall be parked in a designated parking spot, and you will not block or impede us or any other tenants' access to the parking lot or driveways. We may, in our discretion, designate parking areas specific to mopeds, motorcycles and motorized scooters.</p>
    <p>If we authorize your vehicle and you elect to park on the property you agree that we are not liable for any damage, theft, or accident suffered or caused by your vehicle. You agree to indemnify and hold us harmless for any injury to person or property caused by your vehicle.</p>
    <p>If your vehicle damages any property or damages the parking lot, you will be responsible for all costs we incur in correcting said damage.</p>
    <p><strong>DAMAGE FEES:</strong></p>
    <ul>
      <li>Parking lot damage: Cost of repair + $250 administrative fee</li>
      <li>Property damage: Full cost of repair</li>
    </ul>
    <p>You understand and agree that you will not park any disabled, significantly damaged, or other defective vehicles on the Property. You agree and acknowledge that you will provide us with proof of insurance and registration for any vehicles we authorize you to park on the property.</p>
    <p><strong>WE RESERVE THE RIGHT TO TOW ANY VEHICLES ON THE PROPERTY AT YOUR COST WITH OR WITHOUT PRIOR NOTICE IN OUR SOLE AND ABSOLUTE DISCRETION.</strong></p>
    <p><strong>The parking permit must be displayed on the upper driver's side of the windshield at all times.</strong></p>
    <hr>
    <h2>Vehicle Information</h2>
    <p><strong>Make:</strong> <span class="prefilled">${vehicle.make}</span> &nbsp;&nbsp; <strong>Model:</strong> <span class="prefilled">${vehicle.model}</span> &nbsp;&nbsp; <strong>Year:</strong> <span class="prefilled">${vehicle.year}</span></p>
    <p><strong>Color:</strong> <span class="prefilled">${vehicle.color}</span> &nbsp;&nbsp; <strong>License Plate:</strong> <span class="prefilled">${vehicle.plate}</span></p>
    <hr>
    ${signatureBlock(['Tenant Signature', 'Stanton Management -- Approved / Denied'])}
    <p style="margin-top: 16px;"><strong>Notes:</strong> _______________________________________________</p>
    ${footer(date)}
  </body></html>`;
}

// ── Pet Addendum ──

interface PetData {
  type: string;
  breed: string;
  name: string;
  weight: string;
  age: string;
  spayedNeutered: string;
  vaccinesUpToDate: string;
  monthlyFee: number;
  deposit: number;
}

export function renderPetAddendum(data: PrintData, pets: PetData[]): string {
  const date = data.date || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const headers = `<tr><th></th>${pets.map((_, i) => `<th>Pet ${i + 1}</th>`).join('')}${pets.length < 2 ? '<th>Pet 2</th>' : ''}</tr>`;
  const rows = [
    ['Type of Animal', ...pets.map(p => p.type)],
    ['Breed', ...pets.map(p => p.breed)],
    ['Name', ...pets.map(p => p.name)],
    ['Weight (lbs)', ...pets.map(p => p.weight)],
    ['Age', ...pets.map(p => p.age)],
    ['Spayed / Neutered?', ...pets.map(p => p.spayedNeutered)],
    ['Up to date on vaccines?', ...pets.map(p => p.vaccinesUpToDate)],
  ].map(row => {
    let cells = row.slice(1).map(v => `<td class="prefilled">${v}</td>`).join('');
    if (pets.length < 2) cells += '<td></td>';
    return `<tr><td><strong>${row[0]}</strong></td>${cells}</tr>`;
  }).join('');

  const totalMonthly = pets.reduce((s, p) => s + p.monthlyFee, 0);
  const totalDeposit = pets.reduce((s, p) => s + p.deposit, 0);

  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Pet Approval Request / Pet Addendum</title><style>${printStyles()}</style></head><body>
    ${companyHeader()}
    <div class="form-title">Pet Approval Request / Pet Addendum</div>
    ${field('Tenant Name(s)', data.tenantName)}
    ${field('Unit Address', `${data.buildingAddress} - Unit ${data.unitNumber}`)}
    ${field('Date of Request', date)}
    <hr>
    <h2>Pet Fees</h2>
    <table>
      <tr><th>Pet Type</th><th>Weight</th><th>Monthly Rent</th><th>One-Time Deposit</th></tr>
      <tr><td>Cat</td><td>N/A</td><td>$25</td><td>$150</td></tr>
      <tr><td>Small Dog</td><td>Under 25 lbs</td><td>$25</td><td>$200</td></tr>
      <tr><td>Medium Dog</td><td>25-50 lbs</td><td>$35</td><td>$250</td></tr>
      <tr><td>Large Dog</td><td>50+ lbs</td><td>$45</td><td>$300</td></tr>
    </table>
    <hr>
    <h2>Pet Information</h2>
    <table>${headers}${rows}</table>
    <hr>
    <h2>Terms & Conditions</h2>
    <p>By signing below, the tenant agrees to the following:</p>
    <ul>
      <li>Pets must remain approved and on file -- adding a new pet requires a new request</li>
      <li>Tenant is fully responsible for any and all damage caused by their pet</li>
      <li>Tenant is responsible for ensuring their pet does not disturb neighbors</li>
      <li>Unauthorized pets are a lease violation and subject to immediate action</li>
      <li>A pet deposit of <span class="prefilled">$${totalDeposit}</span> is required prior to the pet occupying the unit</li>
      <li>Monthly pet fee of <span class="prefilled">$${totalMonthly}</span> applies (if applicable per lease addendum)</li>
    </ul>
    <hr>
    <h2>Insurance Requirement</h2>
    <div class="callout">
      <p><strong>Pet owners must have $300,000 minimum liability coverage</strong> (standard is $100,000 without pets).</p>
    </div>
    <hr>
    ${signatureBlock(['Tenant Signature', 'Stanton Management -- Approved / Denied'])}
    <p style="margin-top: 16px;"><strong>Notes:</strong> _______________________________________________</p>
    ${footer(date)}
  </body></html>`;
}

// ── No Pets Acknowledgment ──

export function renderNoPetsAcknowledgment(data: PrintData): string {
  const date = data.date || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>No Pets Acknowledgment</title><style>${printStyles()}</style></head><body>
    ${companyHeader()}
    <div class="form-title">No Pets Acknowledgment</div>
    ${field('Tenant Name(s)', data.tenantName)}
    ${field('Unit Address', `${data.buildingAddress} - Unit ${data.unitNumber}`)}
    ${field('Date', date)}
    <hr>
    <h2>Acknowledgment</h2>
    <p>I, <strong>${data.tenantName}</strong>, hereby confirm that I do not currently have any pets (including dogs, cats, birds, reptiles, fish, or any other animals) residing in or regularly visiting my rental unit at <strong>${data.buildingAddress}, Unit ${data.unitNumber}</strong>.</p>
    <h2>Terms</h2>
    <ul>
      <li>If I acquire a pet in the future, I agree to notify management <strong>before</strong> the pet enters the premises and complete a Pet Approval Request.</li>
      <li>Unauthorized pets are a lease violation and may result in fees, fines, or further action.</li>
      <li>Pet fees and deposits apply as outlined in the Pet Addendum — they are <strong>not</strong> waived by prior absence of pets.</li>
    </ul>
    <hr>
    ${signatureBlock(['Tenant Signature', 'Received by (Stanton Management)'])}
    ${footer(date)}
  </body></html>`;
}

// ── Insurance Authorization ──

export function renderInsuranceAuth(data: PrintData, choice: 'own' | 'appfolio', lang: PrintLang = 'en'): string {
  const t = getInsuranceTranslations(lang);
  const date = data.date || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const llcName = findLLCForAddress(data.buildingAddress);

  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${t.authTitle}</title><style>${printStyles()}</style></head><body>
    ${companyHeader()}
    <div class="form-title">${t.authTitle}</div>
    ${field(t.tenantName, data.tenantName)}
    ${field(t.unitAddress, `${data.buildingAddress} - Unit ${data.unitNumber}`)}
    ${field(t.date, date)}
    <hr>
    <h2>${t.authRequirementsHeading}</h2>
    <p>${t.authRequirementsIntro}</p>
    <ul>
      <li><strong>${t.authMinCoverage}</strong></li>
      <li><strong>${t.authUnitAddress}</strong></li>
      <li><strong>${t.authAdditionalInsured}</strong></li>
    </ul>
    <hr>
    <h2>${t.authAdditionalInsuredHeading}</h2>
    <div class="callout">
      <p><strong>${t.authAdditionalInsuredName}</strong></p>
      <p class="prefilled" style="margin-bottom: 10px;">${llcName}</p>
      <p><strong>${t.authAdditionalInsuredAddress}</strong></p>
      <p class="prefilled">421 Park St, Hartford CT 06106</p>
    </div>
    <hr>
    <h2>${t.authSelectOption}</h2>
    <div class="checkbox-row">
      <div class="checkbox ${choice === 'own' ? 'checked' : ''}"></div>
      <div>
        <strong>${t.authOptionATitle}</strong><br>
        ${t.authOptionABody}
      </div>
    </div>
    <div class="checkbox-row" style="margin-top: 16px;">
      <div class="checkbox ${choice === 'appfolio' ? 'checked' : ''}"></div>
      <div>
        <strong>${t.authOptionBTitle}</strong><br>
        ${t.authOptionBBody}
      </div>
    </div>
    <hr>
    ${signatureBlock([t.authTenantSignature, t.authReceivedBy])}
    ${footer(date)}
  </body></html>`;
}

// ── Additional Insured Instructions (full renters insurance info + phone instructions) ──

export function renderAdditionalInsuredInstructions(data: PrintData, lang: PrintLang = 'en'): string {
  const t = getInsuranceTranslations(lang);
  const date = data.date || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const llcName = findLLCForAddress(data.buildingAddress);

  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${t.instrTitle}</title><style>${printStyles()}</style></head><body>
    ${companyHeader()}
    <div class="form-title">${t.instrTitle}</div>
    ${field(t.tenantName, data.tenantName)}
    ${field(t.unitAddress, `${data.buildingAddress} - Unit ${data.unitNumber}`)}
    ${field(t.date, date)}
    <hr>
    <h2>${t.instrWhatIsHeading}</h2>
    <p>${t.instrWhatIsBody}</p>
    <hr>
    <h2>${t.instrRequirementsHeading}</h2>
    <p>${t.instrRequirementsIntro}</p>
    <ul>
      <li><strong>${t.instrReqCoverage}</strong></li>
      <li><strong>${t.instrReqUnitAddress}</strong></li>
      <li><strong>${t.instrReqAdditionalInsured}</strong></li>
    </ul>
    <hr>
    <h2>${t.instrYourLLCHeading}</h2>
    <div class="callout">
      <p><strong>${t.instrAdditionalInsuredName}</strong></p>
      <p class="prefilled" style="margin-bottom: 10px;">${llcName}</p>
      <p><strong>${t.instrAdditionalInsuredAddress}</strong></p>
      <p class="prefilled">421 Park St, Hartford CT 06106</p>
    </div>
    <hr>
    <h2>${t.instrHowToAddHeading}</h2>
    <p><strong>${t.instrCallIntro}</strong></p>
    <div class="callout" style="font-size: 13px; line-height: 1.8;">
      <p><em>${t.instrCallScript}</em></p>
    </div>
    <table>
      <tr><th style="width: 180px;">${t.instrTheyAsk}</th><th>${t.instrYouSay}</th></tr>
      <tr><td><strong>${t.instrAIName}</strong></td><td class="prefilled">${llcName}</td></tr>
      <tr><td><strong>${t.instrAIAddress}</strong></td><td class="prefilled">421 Park St, Hartford CT 06106</td></tr>
      <tr><td><strong>${t.instrRelationship}</strong></td><td>${t.instrRelationshipAnswer}</td></tr>
    </table>
    <hr>
    <h2>${t.instrAfterCallHeading}</h2>
    <ol>
      <li style="margin-bottom: 8px;"><strong>${t.instrAfterCall1}</strong></li>
      <li style="margin-bottom: 8px;"><strong>${t.instrAfterCall2}</strong></li>
    </ol>
    <hr>
    <h2>${t.instrNeedHelpHeading}</h2>
    <p>${t.instrNeedHelp1}</p>
    <p>${t.instrNeedHelp2}</p>
    <hr>
    ${footer(date)}
  </body></html>`;
}

// ── Open print window utility ──

export function openPrintWindow(html: string) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to print forms.');
    return;
  }
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.onload = () => {
    setTimeout(() => printWindow.print(), 300);
  };
}
