// Portfolio mapping from acct_property_master table
// Order: 90 Park, South End Portf., Hartford 1, North End Portf., Park Portfolio

export const buildingToPortfolio: Record<string, string> = {
  "90 Park Street": "90 Park",
  "97-103 Maple Ave": "South End Portf.",
  "222-224 Maple Ave": "South End Portf.",
  "43-45 Franklin Ave": "South End Portf.",
  "47 Franklin Ave": "South End Portf.",
  "15-17 Whitmore Street": "South End Portf.",
  "36 Whitmore Street": "South End Portf.",
  "38-40 Whitmore Street": "South End Portf.",
  "236 Maple Ave": "South End Portf.",
  "228 Maple Ave": "Hartford 1",
  "93-95 Maple Ave": "Hartford 1",
  "110 Martin St": "North End Portf.",
  "120 Martin St": "North End Portf.",
  "152-154 Wooster St": "North End Portf.",
  "160 Wooster St": "North End Portf.",
  "165 Westland St": "North End Portf.",
  "1721-1739 Main St": "North End Portf.",
  "69-73 Chestnut St": "North End Portf.",
  "91 Edwards St": "North End Portf.",
  "31-33 Park St": "Park Portfolio",
  "67-73 Park St": "Park Portfolio",
  "83-91 Park St": "Park Portfolio",
  "57 Park St": "Park Portfolio",
  "10 Wolcott St": "Park Portfolio",
  "179 Affleck St": "Park Portfolio",
  "144-146 Affleck St": "Park Portfolio",
  "178 Affleck St": "Park Portfolio",
  "182 Affleck St": "Park Portfolio",
  "190 Affleck St": "Park Portfolio",
  "195 Affleck St": "Park Portfolio",
  "88-90 Ward St": "Park Portfolio",
  "865 Broad St": "Park Portfolio",
  "142 Seymour St": "Park Portfolio",
  "158 Seymour St": "Park Portfolio",
  "164 Seymour St": "Park Portfolio",
  "167 Seymour St": "Park Portfolio",
  "169 Seymour St": "Park Portfolio",
  "170 Seymour St": "Park Portfolio",
  "180 Seymour St": "Park Portfolio",
  "213-217 Buckingham St": "Park Portfolio",
  "23-31 Squire St": "Park Portfolio",
};

export const portfolioOrder = [
  "90 Park",
  "South End Portf.",
  "Hartford 1",
  "North End Portf.",
  "Park Portfolio",
];

export const portfolioBuildings: Record<string, string[]> = {
  "90 Park": ["90 Park Street"],
  "South End Portf.": [
    "97-103 Maple Ave",
    "222-224 Maple Ave",
    "43-45 Franklin Ave",
    "47 Franklin Ave",
    "15-17 Whitmore Street",
    "36 Whitmore Street",
    "38-40 Whitmore Street",
    "236 Maple Ave",
  ],
  "Hartford 1": ["228 Maple Ave", "93-95 Maple Ave"],
  "North End Portf.": [
    "110 Martin St",
    "120 Martin St",
    "152-154 Wooster St",
    "160 Wooster St",
    "165 Westland St",
    "1721-1739 Main St",
    "69-73 Chestnut St",
    "91 Edwards St",
  ],
  "Park Portfolio": [
    "31-33 Park St",
    "67-73 Park St",
    "83-91 Park St",
    "57 Park St",
    "10 Wolcott St",
    "179 Affleck St",
    "144-146 Affleck St",
    "178 Affleck St",
    "182 Affleck St",
    "190 Affleck St",
    "195 Affleck St",
    "88-90 Ward St",
    "865 Broad St",
    "142 Seymour St",
    "158 Seymour St",
    "164 Seymour St",
    "167 Seymour St",
    "169 Seymour St",
    "170 Seymour St",
    "180 Seymour St",
    "213-217 Buckingham St",
    "23-31 Squire St",
  ],
};
