/**
 * CI guard: verifies lib/buildings.ts is in sync with the database.
 *
 * Generates expected file content in memory (same logic as generate-buildings-ts.ts)
 * and compares it to the current lib/buildings.ts. Exits 1 if stale.
 *
 * Run with: npx tsx scripts/check-buildings-ts.ts
 */

import { config } from 'dotenv';
import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
import { join } from 'path';
import {
  buildingToLLC,
  buildingsWithParking,
  newAcquisitionBuildings,
  appfolioNameToAssetId,
  appfolioNameToAddress,
} from '../lib/buildings';

config({ path: '.env' });
config({ path: '.env.local', override: true });

const cleanEnv = (v: string | undefined) => v?.replace(/^["']|["']$/g, '');

const supabase = createClient(
  cleanEnv(process.env.NEXT_PUBLIC_SUPABASE_URL) || '',
  cleanEnv(process.env.SUPABASE_SERVICE_ROLE_KEY) || ''
);

function naturalCompare(a: string, b: string): number {
  return a.localeCompare(b, 'en', { numeric: true, sensitivity: 'base' });
}

async function main() {
  const assetIdToFormAddress: Record<string, string> = {};
  for (const [afName, assetId] of Object.entries(appfolioNameToAssetId)) {
    const formAddr = appfolioNameToAddress[afName];
    if (!formAddr) throw new Error(`appfolioNameToAddress missing entry for ${afName}`);
    assetIdToFormAddress[assetId] = formAddr;
  }

  const { data: properties, error: propErr } = await supabase
    .from('properties')
    .select('asset_id, address')
    .order('asset_id');
  if (propErr) throw propErr;

  const { data: units, error: unitErr } = await supabase
    .from('unit_bedroom_map')
    .select('asset_id, unit_number')
    .order('asset_id');
  if (unitErr) throw unitErr;

  const buildingsSet = new Set<string>();
  for (const p of properties || []) {
    const formAddr = assetIdToFormAddress[p.asset_id];
    if (!formAddr) {
      console.warn(`No form-canonical address mapping for asset_id ${p.asset_id} (${p.address}); skipping`);
      continue;
    }
    buildingsSet.add(formAddr);
  }
  const buildings = Array.from(buildingsSet).sort(naturalCompare);

  const buildingUnits: Record<string, string[]> = {};
  for (const u of units || []) {
    const formAddr = assetIdToFormAddress[u.asset_id];
    if (!formAddr) continue;
    if (!buildingUnits[formAddr]) buildingUnits[formAddr] = [];
    buildingUnits[formAddr].push(u.unit_number);
  }
  for (const k of Object.keys(buildingUnits)) {
    buildingUnits[k] = buildingUnits[k].sort(naturalCompare);
  }

  const sortedBuildingsWithParking = Array.from(buildingsWithParking).sort(naturalCompare);
  const sortedNewAcquisitionBuildings = Array.from(newAcquisitionBuildings).sort(naturalCompare);

  const out: string[] = [];
  out.push('// AUTO-GENERATED by scripts/generate-buildings-ts.ts');
  out.push('// Regenerate after adding/removing buildings or units in the DB.');
  out.push('// Hand-edit only the policy maps at the bottom (LLC, parking, new acquisition).');
  out.push('');
  out.push('export const buildings = [');
  for (const b of buildings) out.push(`  ${JSON.stringify(b)},`);
  out.push('];');
  out.push('');
  out.push('export const buildingUnits: Record<string, string[]> = {');
  for (const b of buildings) {
    const us = buildingUnits[b];
    if (!us || us.length === 0) {
      out.push(`  ${JSON.stringify(b)}: [],`);
    } else {
      out.push(`  ${JSON.stringify(b)}: [${us.map((u) => JSON.stringify(u)).join(', ')}],`);
    }
  }
  out.push('};');
  out.push('');
  out.push('export const buildingToLLC: Record<string, string> = {');
  for (const b of buildings) {
    const llc = buildingToLLC[b];
    if (llc) out.push(`  ${JSON.stringify(b)}: ${JSON.stringify(llc)},`);
  }
  out.push('};');
  out.push('');
  out.push('export const buildingsWithParking = new Set([');
  for (const b of sortedBuildingsWithParking) out.push(`  ${JSON.stringify(b)},`);
  out.push(']);');
  out.push('');
  out.push('// Park Portfolio - New Acquisition Buildings');
  out.push('export const newAcquisitionBuildings = new Set([');
  for (const b of sortedNewAcquisitionBuildings) out.push(`  ${JSON.stringify(b)},`);
  out.push(']);');
  out.push('');
  out.push('// --- Asset ID Maps (single source of truth for building identity) ---');
  out.push('');
  out.push('export const appfolioNameToAssetId: Record<string, string> = {');
  for (const [k, v] of Object.entries(appfolioNameToAssetId)) {
    out.push(`  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
  }
  out.push('};');
  out.push('');
  out.push('export const appfolioNameToAddress: Record<string, string> = {');
  for (const [k, v] of Object.entries(appfolioNameToAddress)) {
    out.push(`  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
  }
  out.push('};');
  out.push('');
  out.push('export const buildingToAssetId: Record<string, string> = Object.fromEntries(');
  out.push('  Object.entries(appfolioNameToAddress).map(([afName, address]) => [address, appfolioNameToAssetId[afName]])');
  out.push(');');
  out.push('');

  const expected = out.join('\n');
  const filePath = join(process.cwd(), 'lib', 'buildings.ts');
  const actual = readFileSync(filePath, 'utf8');

  if (actual === expected) {
    console.log('✓ lib/buildings.ts is up to date');
    process.exit(0);
  }

  // Print a line-level diff summary
  const expectedLines = expected.split('\n');
  const actualLines = actual.split('\n');
  const maxLines = Math.max(expectedLines.length, actualLines.length);
  const diffLines: string[] = [];
  for (let i = 0; i < maxLines; i++) {
    if (expectedLines[i] !== actualLines[i]) {
      diffLines.push(`  line ${i + 1}:`);
      if (actualLines[i] !== undefined) diffLines.push(`    actual:   ${actualLines[i]}`);
      if (expectedLines[i] !== undefined) diffLines.push(`    expected: ${expectedLines[i]}`);
      if (diffLines.length > 40) { diffLines.push('  ... (truncated)'); break; }
    }
  }

  console.error('✗ lib/buildings.ts is STALE. Run: npx tsx scripts/generate-buildings-ts.ts');
  console.error('');
  console.error('Diff:');
  for (const l of diffLines) console.error(l);
  process.exit(1);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
