/**
 * Regenerates lib/buildings.ts from the database.
 *
 * Reads:
 *   - public.properties (asset_id, address)
 *   - public.unit_bedroom_map (asset_id, unit_number, bedroom_count)
 *
 * Preserves verbatim from the existing lib/buildings.ts:
 *   - buildingToLLC
 *   - buildingsWithParking
 *   - newAcquisitionBuildings
 *   - appfolioNameToAssetId
 *   - appfolioNameToAddress
 *
 * Regenerates from DB:
 *   - buildings (sorted)
 *   - buildingUnits (keyed by the form-canonical address used in project_units.building,
 *     resolved via appfolioNameToAddress, units sorted naturally)
 *   - buildingToAssetId (derived)
 *
 * Run with: npx tsx scripts/generate-buildings-ts.ts
 */

import { config } from 'dotenv';
import { createClient } from '@supabase/supabase-js';
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import {
  buildingToLLC,
  buildingsWithParking,
  newAcquisitionBuildings,
  appfolioNameToAssetId,
  appfolioNameToAddress,
} from '../lib/buildings';

config({ path: '.env' });
config({ path: '.env.local', override: true });

const cleanEnv = (v: string | undefined) => v?.replace(/^["']|["']$/g, '');

const supabase = createClient(
  cleanEnv(process.env.NEXT_PUBLIC_SUPABASE_URL) || '',
  cleanEnv(process.env.SUPABASE_SERVICE_ROLE_KEY) || ''
);

// Natural sort for unit numbers like "1", "2", "10", "1A", "1B", "201", "Retail 1", "COM 67 Park"
function naturalCompare(a: string, b: string): number {
  return a.localeCompare(b, 'en', { numeric: true, sensitivity: 'base' });
}

async function main() {
  // 1. Build asset_id -> form-canonical address (range form, matches project_units.building)
  const assetIdToFormAddress: Record<string, string> = {};
  for (const [afName, assetId] of Object.entries(appfolioNameToAssetId)) {
    const formAddr = appfolioNameToAddress[afName];
    if (!formAddr) {
      throw new Error(`appfolioNameToAddress missing entry for ${afName}`);
    }
    assetIdToFormAddress[assetId] = formAddr;
  }

  // 2. Pull from DB
  const { data: properties, error: propErr } = await supabase
    .from('properties')
    .select('asset_id, address')
    .order('asset_id');
  if (propErr) throw propErr;

  const { data: units, error: unitErr } = await supabase
    .from('unit_bedroom_map')
    .select('asset_id, unit_number')
    .order('asset_id');
  if (unitErr) throw unitErr;

  // 3. Build the buildings list — form-canonical addresses, sorted
  const buildingsSet = new Set<string>();
  for (const p of properties || []) {
    const formAddr = assetIdToFormAddress[p.asset_id];
    if (!formAddr) {
      console.warn(`No form-canonical address mapping for asset_id ${p.asset_id} (${p.address}); skipping`);
      continue;
    }
    buildingsSet.add(formAddr);
  }
  const buildings = Array.from(buildingsSet).sort(naturalCompare);

  // 4. Group units by form-canonical address
  const buildingUnits: Record<string, string[]> = {};
  for (const u of units || []) {
    const formAddr = assetIdToFormAddress[u.asset_id];
    if (!formAddr) continue;
    if (!buildingUnits[formAddr]) buildingUnits[formAddr] = [];
    buildingUnits[formAddr].push(u.unit_number);
  }
  for (const k of Object.keys(buildingUnits)) {
    buildingUnits[k] = buildingUnits[k].sort(naturalCompare);
  }

  // 5. Derive buildingToAssetId from form-canonical address
  const buildingToAssetId: Record<string, string> = {};
  for (const [assetId, formAddr] of Object.entries(assetIdToFormAddress)) {
    buildingToAssetId[formAddr] = assetId;
  }

  // 6. Render the file
  const sortedBuildingsWithParking = Array.from(buildingsWithParking).sort(naturalCompare);
  const sortedNewAcquisitionBuildings = Array.from(newAcquisitionBuildings).sort(naturalCompare);

  const out: string[] = [];
  out.push('// AUTO-GENERATED by scripts/generate-buildings-ts.ts');
  out.push('// Regenerate after adding/removing buildings or units in the DB.');
  out.push('// Hand-edit only the policy maps at the bottom (LLC, parking, new acquisition).');
  out.push('');
  out.push('export const buildings = [');
  for (const b of buildings) out.push(`  ${JSON.stringify(b)},`);
  out.push('];');
  out.push('');
  out.push('export const buildingUnits: Record<string, string[]> = {');
  for (const b of buildings) {
    const us = buildingUnits[b];
    if (!us || us.length === 0) {
      out.push(`  ${JSON.stringify(b)}: [],`);
    } else {
      out.push(`  ${JSON.stringify(b)}: [${us.map((u) => JSON.stringify(u)).join(', ')}],`);
    }
  }
  out.push('};');
  out.push('');
  out.push('export const buildingToLLC: Record<string, string> = {');
  for (const b of buildings) {
    const llc = buildingToLLC[b];
    if (llc) out.push(`  ${JSON.stringify(b)}: ${JSON.stringify(llc)},`);
  }
  out.push('};');
  out.push('');
  out.push('export const buildingsWithParking = new Set([');
  for (const b of sortedBuildingsWithParking) out.push(`  ${JSON.stringify(b)},`);
  out.push(']);');
  out.push('');
  out.push('// Park Portfolio - New Acquisition Buildings');
  out.push('export const newAcquisitionBuildings = new Set([');
  for (const b of sortedNewAcquisitionBuildings) out.push(`  ${JSON.stringify(b)},`);
  out.push(']);');
  out.push('');
  out.push('// --- Asset ID Maps (single source of truth for building identity) ---');
  out.push('');
  out.push('export const appfolioNameToAssetId: Record<string, string> = {');
  for (const [k, v] of Object.entries(appfolioNameToAssetId)) {
    out.push(`  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
  }
  out.push('};');
  out.push('');
  out.push('export const appfolioNameToAddress: Record<string, string> = {');
  for (const [k, v] of Object.entries(appfolioNameToAddress)) {
    out.push(`  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
  }
  out.push('};');
  out.push('');
  out.push('export const buildingToAssetId: Record<string, string> = Object.fromEntries(');
  out.push('  Object.entries(appfolioNameToAddress).map(([afName, address]) => [address, appfolioNameToAssetId[afName]])');
  out.push(');');
  out.push('');

  const filePath = join(process.cwd(), 'lib', 'buildings.ts');
  writeFileSync(filePath, out.join('\n'), 'utf8');

  console.log(`Wrote ${filePath}`);
  console.log(`  buildings: ${buildings.length}`);
  console.log(`  buildingUnits entries: ${Object.keys(buildingUnits).length}`);
  const totalUnits = Object.values(buildingUnits).reduce((s, a) => s + a.length, 0);
  console.log(`  total units: ${totalUnits}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
